#!/bin/sh
set -e

case "$1" in
    configure)
        mkdir -p /var/lib/alfaos/iso /var/lib/alfaos/preseed /var/lib/alfaos/state
        chmod 755 /var/lib/alfaos /var/lib/alfaos/iso /var/lib/alfaos/preseed /var/lib/alfaos/state
        ln -sf /usr/bin/alfaos /alfaos 2>/dev/null || true
        ;;
esac

#DEBHELPER#

exit 0
